asr:
  model: faster-whisper-small-int8
llm:
  path: models/llama-3.2-3b-instruct-q4_ks.gguf
  threads: 4
  ctx: 2048
  n_gpu_layers: 0
cache:
  db: data/m1_cache.db
confidence:
  weights:
    rule_hit: 0.35
    p_llm: 0.25
    c_asr: 0.15
    s_ont: 0.10
    s_ctx: 0.15
  thresholds:
    A: 0.9
    B: 0.7
    C: 0.45
  risk_bumps:
    default: -0.3
localization:
  discharge_languages:
    - en
    - es
pathways:
  enabled: true
privacy:
  offline_only: true
logging:
  audit_log: data/audit.log
planpacks:
  directory: m1/planpacks
templates:
  timezone: UTC
