asr:
  model: faster-whisper-small
  device: cpu
  compute_type: int8
llm:
  path: models/llama-3.2-3b-instruct-q4_ks.gguf
  threads: 4
  ctx: 2048
  n_gpu_layers: 0
  seed: 42
  max_tokens: 512
  temperature: 0.0
cache:
  db: data/m1_cache.sqlite
confidence:
  weights:
    rule_hit: 0.35
    p_llm: 0.25
    c_asr: 0.15
    s_ont: 0.1
    s_ctx: 0.15
  thresholds:
    A: 0.9
    B: 0.7
    C: 0.45
  risk_bumps:
    diabetes: 0.05
    anticoagulation: 0.08
localization:
  discharge_languages:
    - en
    - es
pathways:
  enabled: true
privacy:
  offline_only: true
audit:
  log: logs/chip_audit.jsonl
