# path: config/config.yaml
asr:
  model_dir: models/asr/faster-whisper-small-int8   # local path; no network
  vad: silero
  segment_ms: 20000

llm:
  path: models/llm/llama-3.2-3b-instruct-q4_ks.gguf # local path; no network
  threads: 8
  ctx: 2048
  n_gpu_layers: 8
  temperature: 0.2

cache:
  window_hours: 72
  db: data/chart.sqlite

confidence:
  weights: {rule_hit: 0.35, p_llm: 0.25, asr: 0.15, ontology: 0.10, context: 0.15}
  thresholds: {auto_accept: 0.90, soft_confirm: 0.70, must_confirm: 0.45}
  risk_bumps: {high: 0.05, medium: 0.03}

localization:
  discharge_languages: ["en","es"]
  default: "en"

pathways:
  enabled: ["chest_pain","seizure","sepsis"]

privacy:
  offline_only: true
  log_retention_days: 30
