# path: config/logging.yaml
version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
  uvicorn:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    level: INFO
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: false
  uvicorn.access:
    level: WARNING
    handlers: [console]
    propagate: false
  backend:
    level: INFO
    handlers: [console]
    propagate: false
  backend.services:
    level: INFO
    handlers: [console]
    propagate: false
  backend.api:
    level: INFO
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console]
